<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product = $block->getProduct();
$id = $_product->getId();
$quantity = $block->getStockItem($id);

$isValutationProduct = $block->isValutationProduct($_product);

$active = $this->helper('Drc\PreOrder\Helper\Check')->checkEnable();
$buttonTitle = $block->getPreorderButtonText();
?>

<!-- if it's a valutation product -->
<?php if ($isValutationProduct):
    $likes = $_product->getData("valutation_product_likes");
    $buttonTitle = __("Like");
    ?>
    <div class="stock available">
        <span><?= $likes; ?> Likes</span>
    </div>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <button type="submit" title="<?php echo $buttonTitle ?>"
                        class="action primary tocart"  id="product-addtocart-button">
                    <span><?php echo __($buttonTitle); ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php else: ?>

    <?php if (($_product->isSaleable()) || (($active == 1))): ?>
        <div class="box-tocart">
            <div class="fieldset">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?php /* @escapeNotVerified */
                                echo __('Qty'); ?></span></label>
                        <div class="control">
                            <input type="number" name="qty" id="qty" maxlength="12"
                                   value="<?php echo $block->getProductDefaultQty() * 1 ?>"
                                   title="<?php echo __('Qty') ?>" class="input-text qty"
                                   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"/>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo __($buttonTitle); ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?php echo __($buttonTitle); ?></span>
                    </button>
                    <?php echo $block->getChildHtml('', true) ?>
                </div>
            </div>
        </div>

        <!-- Order Progress Bar -->
        <?php if (($active == 1) && $_product->getData('bid_target') >= 0 && $_product->getData('bid_end_date') >= date("Y-m-d")) {
            $ordini = $_product->getData('bid_target'); ?>

            <div class="product-item-link center-text" id="bid-time" style="text-align: center;"
                 href="<?php /* @escapeNotVerified */
                 echo $_product->getProductUrl() ?>">
                <div class="swatch-option bid-alert-bar-color">
                    Scade tra: <strong id="bid-timer" data-bidend="<?= $_product->getData('bid_end_date') ?>"></strong>
                </div>
            </div><br>
            <div class="stock available">
                <span><?php echo $ordini . $block::ORDINI_RAGGIUNTI;?></span>
                <div>
                    <progress value="<?= $ordini; ?>" max="<?= $quantity; ?>" style="width: 100%"></progress>
                </div>
                <span><?php echo $block::ORDINI_RIMASTI;
                        echo  $quantity - $ordini;
                        echo $block::ORDINI_MANCANTI; ?></span>
            </div><br>
        <?php } ?>
    <?php endif; ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    </script>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }

        </script>

    <?php endif; ?>
<?php endif; ?>
</script>
<script type = "text/javascript" >
    function settimer() {
        var prod = document.getElementById('bid-timer');
        var end = new Date(prod.dataset.bidend);
        var second = 1000;
        var minute = second * 60;
        var hour = minute * 60;
        var day = hour * 24;
        var now = new Date();
        var remain = end - now;
        if (remain < 0) {
            clearInterval(timer);
            // Qua deve scattare il trigger di fine bid
            prod.innerHTML = 'Concluso!';
            return;
        }
        var days = Math.floor(remain / day);
        var hours = Math.floor((remain % day) / hour);
        var minutes = Math.floor((remain % hour) / minute);
        var seconds = Math.floor((remain % minute) / second);

        document.getElementById('bid-timer').innerHTML =
            days + ' G ' + hours + ' h ' + minutes + ' n ' + seconds + ' s';
    }

timer = setInterval(settimer, 1000);

</script>
