<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_item = $block->getItem();
$flag=false; ?>
<tr>
    <td class="col-product"><?php echo $block->getColumnHtml($_item, 'name') ?></td>
    <td class="col-ordered-qty"><?php echo $block->getColumnHtml($_item, 'qty') ?></td>
    <?php 
            
            $id = $_item->getData('product_id'); 
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
             $obj=$objectManager->create('Magento\CatalogInventory\Model\Stock\StockItemRepository')->get($id);
                        $backorderStatus=$obj->getData('backorders');
                        $stockStatus=$obj->getIsInStock();
            if (($backorderStatus=='3' && $stockStatus=='1') || ($backorderStatus=='4' && $stockStatus==NULL ) ) {
                $flag=true;
            }
            if ($flag=='true'): ?>
               <td class="col-qty last"> <span  style="font-weight:bold" >"product is Pre-Order and cannot be shipped" </span>
              <input type="hidden" name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]" value="0" />
               </td>
           <?php else: ?>
    <td class="col-qty <?php if ($block->isShipmentRegular()): ?>last<?php endif; ?>">
        

        <?php if ($block->canShipPartiallyItem()): ?>

            
            <input type="text"
                   class="input-text admin__control-text qty-item"
                   name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]"
                   value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>" />
              
        <?php else: ?>
            <?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>
        <?php endif; ?>
    </td>
    <?php if (!$block->canShipPartiallyItem()): ?>
    <td class="col-ship last">
        <input type="hidden" name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]" value="0" />
        <input type="checkbox" name="shipment[items][<?php /* @escapeNotVerified */ echo $_item->getOrderItemId() ?>]" value="<?php /* @escapeNotVerified */ echo $_item->getQty()*1 ?>" checked />
    </td>
    <?php endif; ?>
<?php endif; ?>
</tr>
