<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
    <?php
    $type = 'widget-product-grid';
    $mode = 'grid';
    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $showWishlist = false;
    $showCompare = false;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $active = boolval($this->helper('Drc\PreOrder\Helper\Check')->checkEnable());

    ?>
    <div class="block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title):?>
            <div class="block-title">
                <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <ol class="product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">

                            <?php // Product Timer ?>
                            <?php if ($block->showTimerBar($_item)) { ?>
                                <div class="product-item-link center-text" id="bid-time" style="text-align: center;"
                                     href="<?php /* @escapeNotVerified */ echo $_item->getProductUrl() ?>">
                                    <div class="swatch-option color" style="background-color: #eb6703;color: #FFFFFF;max-width: 100%;text-align: center;float: inherit;">
                                        <?php /* @escapeNotVerified */ echo __('Scade tra: ') ?><strong id="bid-timer-<?=$_item->getSku()?>"
                                                                                                        data-bidend="<?=$_item->getData('bid_end_date')?>"></strong>
                                    </div>
                                </div>

                            <?php } ?>


                            <?php // Product Image ?>
                            <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <?php if ($active && (int)$_item->getData('bid_target') >= 0 ) {
                                        $ordini = $block->getMembershipNumber($_item);
                                        $quantita =  $block->getQty($_item->getId());
                                        ?>
                                        <div class="stock available">
                                            <div style="text-align: center">
                                                <strong><?=$ordini?> / <?=$quantita?></strong> <?php /* @escapeNotVerified */ echo __('adesioni raggiunte') ?>
                                                <progress value="<?=$ordini?>" max="<?=$quantita?>" style="width: 100%"></progress></div>
                                        </div><br>
                                    <?php } ?>

                                    <a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>

                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __($block->getButtonText($_item->getTypeId())) ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __($block->getButtonText($_item->getTypeId())) ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                                type="button" title="<?php /* @escapeNotVerified */ echo __($block->getButtonText($_item->getTypeId())) ?>">
                                                            <span><?php /* @escapeNotVerified */ echo __($block->getButtonText($_item->getTypeId())) ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>


<script type="text/javascript">


    require(['jquery'], function($){
        $( document ).ready(function() {
            function bidCountdown() {
                $('#bid-time [id^="bid-timer-"]').each(function () {
                    var id = this.id;
                    var val = $(this).data("bidend").split(" ");
                    var end = new Date(val[0]);
                    var second = 1000;
                    var minute = second * 60;
                    var hour = minute * 60;
                    var day = hour * 24;
                    var now = new Date();
                    var remain = end - now;
                    if (remain < 0) {
                        clearInterval(timer);
                        // Qua deve scattare il trigger di fine bid
                        document.getElementById(id).innerHTML = 'Concluso!';
                        return;
                    }
                    var days = Math.floor(remain / day);
                    var hours = Math.floor((remain % day) / hour);
                    var minutes = Math.floor((remain % hour) / minute);
                    var seconds = Math.floor((remain % minute) / second);

                    document.getElementById(id).innerHTML =
                        days + ' G ' + hours + ' h ' + minutes + ' m ' + seconds + ' s';
                });
            }
            setInterval(bidCountdown, 1000); // update every second
        });

    });
</script>