<?php
$categories = $this->getCategoryCollection();
$canShowImg = $this->canShowImage();
?>

<div class="columns">
<div class="block widget block-products-list grid">
        <div class="block-content">
            <div class="products wrapper grid products-grid">
                <ol class="products list items product-items">
                    <?php foreach($categories as $category):?>
                    <li class="item product product-item">
                        <div class="product-item-info" data-container="product-grid">
                            <?php if($canShowImg && $category->getImageUrl()):?>
                            <a href="<?php echo $block->escapeUrl($category->getUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
                                <span class="product-image-container" style="<?=$this->getImageWidth();?>">
                                    <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                        <img class="product-image-photo"
                                             src="<?php echo $block->escapeUrl($category->getImageUrl()) ?>""
                                             width="<?=$this->getImageWidth();?>"
                                             height="<?=$this->getImageHeight()?>"
                                             alt="<?php echo $block->escapeHtml($category->getName()) ?>">
                                    </span>
                                </span>
                            </a>
                            <?php endif;?>
                            <div class="product details product-item-details">
                                <h2 class="product name product-item-name">
                                    <a class="product-item-link" href="<?php echo $block->escapeUrl($category->getUrl()) ?>">
                                        <?php echo $block->escapeHtml($category->getName()) ?>
                                    </a>
                                </h2>

                                <?php
                                $childrenCategories = $category->getChildrenCategories();
                                if(!empty($childrenCategories)): ?>
                                <ul>
                                    <?php foreach( $childrenCategories as $childCategory):?>
                                    <li>
                                        <h3 class="product name product-item-name">
                                            <a class="product-item-link" href="<?php echo $block->escapeUrl($childCategory->getUrl()) ?>">
                                                <?php echo $block->escapeHtml($childCategory->getName()) ?>
                                            </a>
                                        </h3>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endif; ?>

                            </div>
                        </div>
                    </li>
                    <?php endforeach; ?>
                </ol>
            </div>
        </div>
</div>

</div>
</div>


