<?php


$customer_id = $block->getCustomerId();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\CatalogInventory\Api\StockStateInterface');

$imageHelperFactory = $objectManager->create("\Magento\Catalog\Helper\ImageFactory");

/**
 * @TODO Da cambiare costante cablata
 */
$store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
$base_url = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
            ->getStore(1)
            ->getBaseUrl();


$GDArepo = $objectManager->get('\Drc\PreOrder\Model\PreorderPending');
$productFactory = $objectManager->get('\Magento\Catalog\Model\ProductFactory');

$prodotti = array();
$gda = $GDArepo->getProductsByIdCustomer($customer_id);

foreach($gda as $prodotto){
	$prodotti[$prodotto['id_prodotto']] = $prodotto; 	
}

?>


<div class="admin__data-grid-wrap" data-role="grid-wrapper">
    <table class="data-grid data-grid" data-role="grid">
		<thead>
            <tr data-bind="">
				<th class="data-grid-th " data-bind="">
    				<span class="data-grid-cell-content" data-bind="">Gruppi di Acquisto</span>
				</th>
			</tr>
		 </thead>
		 <tbody>
		<?php
		if(count($prodotti)>0){
			foreach($prodotti as $prod){
				
				$prodotto = $productFactory->create()->load($prod['id_prodotto']); //oggetto prodotto
				$nome_prodotto = $prodotto->getName();
     			$prezzo =  $prodotto->getPrice();
      		    $imageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $prodotto->getImage();
				
				$bid_prodotto = $prodotto->getResource()->getAttribute("bid_target")->getFrontend()->getValue($prodotto); //bid
        		$bid_start_date = $prodotto->getResource()->getAttribute("bid_start_date")->getFrontend()->getValue($prodotto);
        		$bid_end_date = $prodotto->getResource()->getAttribute("bid_end_date")->getFrontend()->getValue($prodotto);
				
				$date = new DateTime($bid_start_date);
				$bid_start_date = $date->format('d-m-Y');
				
				$date = new DateTime($bid_end_date);
				$bid_end_date = $date->format('d-m-Y');
				
     		    $soglia = $StockState->getStockQty($prodotto->getId(), $prodotto->getStore()->getWebsiteId());

				$raggiunto = $bid_prodotto == $soglia ? 1:0;

			?>
	    	<tr class="data-row" data-bind="" data-repeat-index="0">
				<td data-bind="">
					<div class="data-grid-cell-content" data-bind="">
						<img class="admin__control-thumbnail" data-bind="" src="<?= $imageUrl ?>" alt="" style="width:15%; float:left">
						<span style="margin-left:10px"><strong><?= $nome_prodotto; ?> </strong><br></span>
						<span style="margin-left:10px">Data Inizio: <strong><?= $bid_start_date ; ?></strong><br></span>
						<span style="margin-left:10px">Data Fine: <strong><?= $bid_end_date ; ?></strong><br></span>
						<span style="margin-left:10px"><strong><?= round($prezzo,2) ; ?>&nbsp;€ </strong><br></span>
						<span style="margin-left:10px; <?php echo $raggiunto == 1 ? 'color:green' : 'color:red' ?>"><strong><?= $raggiunto == 1 ? "GDA RAGGIUNTO" : "GDA NON RAGGIUNTO" ?></strong><br></span>
												<span style="float:right"><a href="<?= $base_url; ?>admin/catalog/product/edit/id/<?= $prod['id_prodotto']; ?>">Visualizza</a></span>

					</div>
				</td>
			</tr>
			<?php }
		}else{
			?>
			 	    	<tr class="data-row" data-bind="" data-repeat-index="0">
				<td data-bind="">
					<div class="data-grid-cell-content" data-bind="">
						L'utente non ha aderito a nessun GDA.
					</div>
				</td>
			</tr>
			 <?php
		}
		?>
		
		
		 </tbody>
	</table>
</div>
